### ISSUE TITLE
Some API methods incorrectly omit auth token

### ISSUE THREAD

**Issue by DecibillyJoel** [Kalshi/kalshi-python#1]
For example, get_markets() always returns a 401 error because the code generated by swagger passes empty auth settings into api_call()
https://github.com/Kalshi/kalshi-python/blob/main/kalshi_python/api/market_api.py#L536

This is the only one I've encountered so far but will update if I run into any more

**Comment by DecibillyJoel** [comment]
get_market_orderbook suffers the safe issue

**Comment by hsousak** [comment]
Thats solved as well in the latest release, thanks again.

Just do: 

`pip install kalshi-python==2.0.0`

And you should be fine, it had to be a major release because we discontinued some of the enums we were using for the statuses.

I've added all the end-points that you had trouble with to the main example, so I know for a fact they are running now.

Please do open an issue again if u still have trouble.
